site_name: Platinum Renegade
site_url: https://akeemallen.github.io/platinum-renegade
site_description: My iteration of a platinum renegage wiki
site_author: AkeemAllen
repo_url: https://github.com/AkeemAllen/platinum-renegade
theme:
  name: material
  features:
  - content.tabls.links
  - content.tooltips
  favicon: img/items/poke-ball.png
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: black
    scheme: default
    toggle:
      icon: material/eye
      name: Switch to light mode
nav:
- Home: index.md
- Pokemon: []
- Routes:
  - Route 201: routes/Route 201.md
  - Route 202: routes/Route 202.md
  - Jubilife City Trainer School: routes/Jubilife City Trainer School.md
  - Oreburgh Gym: routes/Oreburgh Gym.md
  - Eterna Gym: routes/Eterna Gym.md
  - Hearthome Gym: routes/Hearthome Gym.md
plugins:
- search:
    lang: en
markdown_extensions:
- admonition
- abbr
- attr_list
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
extra_css:
- stylesheets/extra.css
